# Generated by Django 5.1.3 on 2024-11-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='static/img/user-icon.jpg', upload_to='profile_pics/'),
        ),
    ]
